name: Production
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: workzio
   
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          path: "main"
         
      - name: Install Packages & Setup
        run: |
         cd main
         mvn clean install
         sudo service billing restart
         sudo service nginx restart
